### ISSUE TITLE
TypeError in numpy.rate when using Decimals

### ISSUE THREAD

**Issue by meunomemauricio** [numpy/numpy-financial#19]
`numpy.rate` is raising `TypeError` when working with `Decimals` and the iterative function doesn't converge before the max iterations. 

I poked it a little bit, and it seems like the function assumes `rn` to be an array or `float`, but it is a `Decimal`:

https://github.com/numpy/numpy/blob/cacdf265755ffae9d5c07d35fafa3d1366e342b8/numpy/lib/financial.py#L640-L648

### Reproducing code example:

```python
import numpy as np
from decimal import Decimal

np.rate(Decimal(12), Decimal('400'), Decimal('10000'), Decimal(0))
```

`float`s work just fine:

```python
>>> np.rate(12.0, 400.0, 10000.0, 0.0)
nan
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mauricio/.virtualenvs/unhaggle/local/lib/python2.7/site-packages/numpy/lib/financial.py", line 648, in rate
    return np.nan + rn
TypeError: unsupported operand type(s) for +: 'float' and 'Decimal'
```

### Numpy/Python version information:

```
('1.16.3', '2.7.15+ (default, Nov 27 2018, 23:36:35) \n[GCC 7.3.0]')
```

**Comment by Kai-Striega** [comment]
There are two open PRs that could close this the original PR [numpy/numpy#14645](https://github.com/numpy/numpy/pull/14645) by @mandeep001 and  [numpy/numpy#14695](https://github.com/numpy/numpy/pull/14695) that I submitted later, not realising an open one existed. At the time, I closed my PR prefering to give the original author the chance to have their PR merged. Since then [numpy/numpy#14645](https://github.com/numpy/numpy/pull/14645) has stalled with the last commit being on the 8/10. 

@WarrenWeckesser @eric-wieser In the interest of closing this issue, if the original PR isn't merged in a reasonable time (i'll leave the definition of "reasonable" to you), could we look at migrating [numpy/numpy#14695](https://github.com/numpy/numpy/pull/14695)?

**Comment by WarrenWeckesser** [comment]
>  In the interest of closing this issue, if the original PR isn't merged in a reasonable time (i'll leave the definition of "reasonable" to you), could we look at migrating numpy/numpy#14695?

I've asked @Mandeep0001 if he would be willing to start a new pull request in this repository.  If he's not interested in continuing the work, then we can definitely migrate your pull request.

**Comment by Kai-Striega** [comment]
Closing as #20 has been merged.
