### ISSUE TITLE
DOC: How to install docs dependencies and build documentation with poetry

### ISSUE THREAD

**Issue by melissawm** [numpy/numpy-financial#89]
### Issue with current documentation:

There's no details on installing the documentation dependencies such as sphinx and the pydata-sphinx-theme in the development docs.

### Idea or request for content:

Add page describing how to build the docs locally.

**Comment by Kai-Striega** [comment]
I've been holding off on writing this due to some complications in the interaction with Poetry and the current makefile we have set up.

Poetry has the concept of a [dependency group](https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups). This means we can install the `doc` group with ``poetry install --with docs``.  However the makefile is still set to run with pip. The makefile should be edited to work with Poetry _before_ we document how to set up the docs.
